### ISSUE TITLE
 Error occurred when install pod.

### ISSUE THREAD

**Issue by DeveloperLx** [beardo/OpenSSL-iOS#1]
When I install it by CocoaPods,
use command in Podfile:
    pod 'OpenSSL-iOS', '~> 1.0.204'
then run on terminal:
   pod install

It reports:

[!] /bin/bash -c 
set -e
    ARCHS="i386 x86_64 armv7 armv7s arm64"

    BASEPATH="${PWD}"
    BUILDDIR="${TMPDIR}OpenSSL"
    SRCDIR="${BUILDDIR}/src"

    SDK_VERSION=`xcrun --sdk iphoneos --show-sdk-version`
    CLANG=`xcrun --find clang`
    DEVELOPER=`xcode-select --print-path`

    rm -rf "${BUILDDIR}"
    mkdir -p "${SRCDIR}"
    cp -R "${BASEPATH}/." "${SRCDIR}"
    cd "${SRCDIR}"

    for ARCH in ${ARCHS}
    do
      if [ "${ARCH}" == "i386" -o "${ARCH}" == "x86_64" ];
      then
        PLATFORM="iPhoneSimulator"
      else
        sed -ie "s!static volatile sig_atomic_t intr_signal;!static volatile intr_signal;!" "${SRCDIR}/crypto/ui/ui_openssl.c"
        PLATFORM="iPhoneOS"
      fi

      CONF="no-asm"

      if [ "${ARCH}" == "arm64" -o "${ARCH}" == "x86_64" ];
      then
        HOST="BSD-generic64"
        CONF="${CONF} enable-ec_nistp_64_gcc_128"
      else
        HOST="BSD-generic32"
      fi

      OPENSSLDIR="${BUILDDIR}/${PLATFORM}${SDK_VERSION}-${ARCH}"

      LIPO_LIBSSL="${LIPO_LIBSSL} ${OPENSSLDIR}/lib/libssl.a"
      LIPO_LIBCRYPTO="${LIPO_LIBCRYPTO} ${OPENSSLDIR}/lib/libcrypto.a"

      rm -rf "${OPENSSLDIR}"
      mkdir -p "${OPENSSLDIR}"

      LOG="${OPENSSLDIR}/build.log"

      export DEVROOT="${DEVELOPER}/Platforms/${PLATFORM}.platform/Developer"
      export SDKROOT="${DEVROOT}/SDKs/${PLATFORM}${SDK_VERSION}.sdk"
      export CC="${CLANG}"

      ./Configure ${HOST} ${CONF} --openssldir="${OPENSSLDIR}" > "${LOG}" 2>&1

      sed -ie "s!^CFLAG=!CFLAG=-isysroot ${SDKROOT} -arch ${ARCH} -mios-version-min=7.0 !" "Makefile"

      make >> "${LOG}" 2>&1
      make all install_sw >> "${LOG}" 2>&1
      make clean >> "${LOG}" 2>&1
    done

    rm -f "${BASEPATH}/libssl.a"
    rm -f "${BASEPATH}/libcrypto.a"
    lipo -create ${LIPO_LIBSSL}    -output "${BASEPATH}/libssl.a"
    lipo -create ${LIPO_LIBCRYPTO} -output "${BASEPATH}/libcrypto.a"

    cp -RL "${SRCDIR}/include/." "${BASEPATH}/"

    cd "${BASEPATH}"
    rm -rf "${BUILDDIR}"

    MODULE="module.modulemap"
    BEFORE_HEADERS="rc2.h rc4.h"
    AFTER_HEADERS="dtls1.h"
    EXCLUDE_HEADERS="${BEFORE_HEADERS} ${AFTER_HEADERS}"

    function print_submodule {
        echo -e "    explicit module $(basename $1 | cut -d"." -f1) {
        header \"$1\"
    }
"
    }

    echo "module OpenSSL {" > $MODULE

    for HEADER in openssl/*.h; do
        if [[ $BEFORE_HEADERS =~ $(basename $HEADER) ]]; then
          print_submodule $HEADER >> $MODULE
        fi
    done

    for HEADER in openssl/*.h; do
        if [[ ! $EXCLUDE_HEADERS =~ $(basename $HEADER) ]]; then
          print_submodule $HEADER >> $MODULE
        fi
    done

    for HEADER in openssl/*.h; do
        if [[ $AFTER_HEADERS =~ $(basename $HEADER) ]]; then
          print_submodule $HEADER >> $MODULE
        fi
    done

    echo -e "    link \"ssl\"
    link \"crypto\"
}" >> $MODULE

xcrun: error: SDK "iphoneos" cannot be located
xcrun: error: SDK "iphoneos" cannot be located
xcrun: error: unable to lookup item 'SDKVersion' in SDK 'iphoneos'

**Comment by beardo** [comment]
Yeah sorry I never got this to work. There is another project that did so if try `pod 'OpenSSL'` you might have better luck.
